### ISSUE TITLE
only getting sound notification, not the visual in the notification bar at top of android

### ISSUE THREAD

**Issue by paruthidotexe** [Agasper/unity-android-notifications#5]
only getting sound notification for the demo scene, not the visual in the notification bar at top of android
config
version : unity5.2
OS : Nexus 7 (2012),   android 5.1.1

**Comment by THIRDCOKE** [comment]
I found the issue - program can't find program icon for notification.
You're using unity 5.2 so you must seen this

"OBSOLETE - Providing Android resources in Assets/Plugins/Android/res is deprecated, please move your resources to an Android Library"

So that's why the plugin doesn't work. 
In Java source code you could see 
```
builder.setSmallIcon(res.getIdentifier(s_icon, "drawable", context.getPackageName()));
```
That's the reason.
For more information about this piece of code please visit the website below, you'll understand what I'm talking about.
http://answers.unity3d.com/questions/398209/android-notification-in-a-plugin.html

If you provide a static int here such as "0x7f020000"
```
builder.setSmallIcon(0x7f020000);
```
You'll notice the plugin worked.

I'm trying to find a new way to get game icon now....

**Comment by Agasper** [comment]
You can build plugin with you own icons, or still get obsolete warning
